# jpa
spring:
  application:
    name: demoshop

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${DB_URL}  # DB URL을 환경 변수로 처리
    username: ${DB_USERNAME}  # Secrets에서 가져오기
    password: ${DB_PASSWORD}  # Secrets에서 가져오기
    driver-class-name: com.mysql.cj.jdbc.Driver

  # cloud
  cloud:
    gcp:
      storage:
        credentials:
          location: ${GCP_CREDENTIALS_PATH}  # GCP 인증 파일 경로를 환경 변수로 처리
        project-id: daily-commit-424306
        bucket: java-board-bucket

  jwt:
    secret: ${JWT_SECRET}  # JWT secret을 환경 변수로 처리

  # swagger
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2

  api-docs:
    path: /api-docs

  show-actuator: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**

# log
logging:
  level:
    org.springframework.security: DEBUG
