# jpa
spring:
  profiles:
    include: secret  # 민감정보 secret 파일

  application:
    name: demoshop

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true


  # swagger
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2

  api-docs:
    path: /api-docs

  show-actuator: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**

# log
logging:
  level:
    org.springframework.security: DEBUG
