name: Java CI with Gradle

# 동작 조건 설정: develop 브랜치에 push or pull request가 발생할 경우 동작
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  # Spring Boot 애플리케이션을 빌드하여 Docker Hub에 Push하는 과정
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    # 1. Java 21 세팅
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    # GCP json 파일 설정
    - name: Set up GCP credentials
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > ./src/main/resources/daily-commit-424306-fcc0c61d0682.json

    # yml 변수 설정
    - name: Set up environment variables
      run: |
        echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
        echo "GCP_CREDENTIALS_PATH=${{ secrets.GCP_CREDENTIALS_PATH }}" >> $GITHUB_ENV

    # 2. gradlew 권한 부여
    - name: Run chmod to make gradlew executable
      run: chmod +x gradlew
    
    # 3. Spring Boot 애플리케이션 빌드
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      
    # 4. Docker 이미지 빌드 & Push
    - name: Docker Image Build & Push
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sanrio_server .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/sanrio_server


  # 위 build-docker-image 작업에서 Push한 이미지를 EC2에서 Pull & Run시키는 과정 
  run-docker-image-on-ec2:
    # build-docker-image 작업이 완료되어야 실행됨
    needs: build-docker-image

    # self-hosted-runner에서 동작
    runs-on: self-hosted

    steps:
    # 1. 최신 이미지 Pull
    - name: Docker login & pull the image
      run: |
        sudo chmod 666 /var/run/docker.sock
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sanrio_server
      
    # 2. 기존 컨테이너 중지 (실행 중인 컨테이너가 있다면 종료)
    - name: Stop running container
      run: |
        CONTAINER_ID=$(docker ps -q --filter "ancestor=${{ secrets.DOCKERHUB_USERNAME }}/sanrio_server")
        if [ ! -z "$CONTAINER_ID" ]; then
          docker stop "$CONTAINER_ID"
        fi

    # 3. 최신 이미지로 새 컨테이너 실행
    - name: Run new container from pulled image
      run: |
        docker run --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/sanrio_server
